const Keys = {
    "about": "about",
    "home": "home",
    "language": "language",
    "volume":"volume",
    "language_chinese": "language.chinese",
    "language_english": "language.english",
    "languages": "languages",
    "login": "login",
    "login_history": "login_history",
    "logout": "logout",
    "me": "me",
    "settings": "settings",
    "changerate":"changerate",
    "Kline":"Kline",
    "name":"name",
    "latest_price":"latest_price",
    "Fixed Entrust":"Fixed Entrust",
    "Amount":"Amount",
    "Buy":"Buy",
    "Sell":"Sell",
    "Volume":"Volume",
    "Price":"Price"
};
export default Keys;
