const Keys = {
    "Amount": "Amount",
    "Buy": "Buy",
    "Fixed Entrust": "Fixed Entrust",
    "Kline": "Kline",
    "Price": "Price",
    "Sell": "Sell",
    "Volume": "Volume",
    "about": "about",
    "assets": "assets",
    "changerate": "changerate",
    "home": "home",
    "language": "language",
    "language_chinese": "language.chinese",
    "language_english": "language.english",
    "languages": "languages",
    "latest_price": "latest_price",
    "login": "login",
    "login_history": "login_history",
    "logout": "logout",
    "me": "me",
    "name": "name",
    "settings": "settings",
    "ExchangeAmount":"Exchange Amount",
    "OTC":"OTC",
    "volume": "volume",
    "delete": "delete",
    "Transaction":"Transaction",
    "Current_Commission":"Current Commission",
};
export default Keys;
