const userActionTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    UPDATE_USER_INFO: "UPDATE_USER_INFO",
    UPDATE_USER_PASSWORD: "UPDATE_USER_PASSWORD",
    UPDATE_HTTP_REQUEST_COOKIE: "UPDATE_HTTP_REQUEST_TOKEN",
    RECORD_LOGIN_HISTORY: "RECORD_LOGIN_HISTORY",
};

export default userActionTypes;
